### ISSUE TITLE
records: add --no-validation mode

### ISSUE THREAD

**Issue by tomaszgy** [inveniosoftware/invenio-records#122]
In the migrator of INSPIRE legacy records we found it useful to have _--no-validate_ mode in both Record.create() and Record.commit() methods that would skip validating record against JSON Schema. The reason behind this utility is that we sometimes want to migrate legacy record even if it breaks the schema.

If you find it also useful I may open PR with the implementation of the utility as it seems to be a few-lines patch.

**Comment by tiborsimko** [comment]
What about not adding any `$schema` to the record JSON in this case, since the record is known not to follow that schema? (You could store any free JSON in that way...)

**Comment by jmartinm** [comment]
> What about not adding any $schema to the record JSON in this case, since the record is known not to follow that schema? (You could store any free JSON in that way...)

AFAIK that was considered as an option but `invenio-indexer` and friends depend on that field being filled in order to decide which ES index to use.

**Comment by tiborsimko** [comment]
Wouldn't you want fix the schema as soon as possible after the record is uploaded?  

- In theory, one could write a custom enhancing/dispatching rules e.g. taking any JSON field for Elasticsearch indexing, we used to have an example in the past. 

- In practice, one wants to use schemas everywhere ASAP, which is good for indexing, display, etc.

- Philosophically speaking, if a certain input stream promises conformance to some schema, then it should keep up its promise; otherwise all schema declarations kind of loose their sense, as you wouldn't know which ones to trust...

**Comment by lnielsen** [comment]
Zenodo migration I handle with:
1) Import JSON without $schema
2) Migrate JSON by adding $schema and making sure it validates.
3) Index the records.

What about that you just make a dummy schema:
records/dummy-v1.0.0.json
and a normal schema:
records/record-v1.0.0.json

The dummy schema could allow everything and hence validate your bad records. RecordIndexer will put them to their own index, but add the alias `records` so they are searchable.

Anyway, if a record doesn't validate according to your schema ``records/record-v1.0.0.json`` you risk that then your ES mapping will also get messed up.

**Comment by jirikuncar** [comment]
IMHO this feature would only cause problems in modules that rely on the fact that `$schema` is specified and record is validated. As a workaround with dummy schema exists I am in favor of closing this issue.
