### ISSUE TITLE
records: dealing with hidden fields

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-records#13]
Very often we are going to deal with fields that are part of the metadata but that should be kept hidden from not authorized users.
Since `invenio-records` is at the core of the information sent for indexing to elasticsearch, and to display to the format layer, is it worth considering at this level the possibility of declaring certain fields as hidden (e.g. with an additional non standard property), and have invenio-records exposing them only with an opt-in flag? Otherwise, what alternative solutions to this requirement are available?

**Comment by kaplun** [comment]
See also: http://grokbase.com/t/gg/json-schema/13ac6gxqrs/propose-hidden and the `hidden` editor option for `json-editor`: https://github.com/jdorn/json-editor#editor-options

**Comment by jirikuncar** [comment]
This can be solved as part of `formatter` module (possibly *Jinja* filter).

**Comment by kaplun** [comment]
Wouldn't then be required to enforce the "hidden" property explicitly in all formats (thus risking to forget some of them?)

**Comment by tiborsimko** [comment]
Since authorised people may want to search in hidden fields, etc, it is good to send all fields to ES.  The formatter could then take "full JSON", strip away hidden and/or unauthorised fields, and show the user only white-listed information.  If this filtering happens as the first JSON unpacking step, we don't have to do this in all formats separately.

**Comment by lnielsen** [comment]
Moved to inveniosoftware/invenio-records-rest#11
