### ISSUE TITLE
Configurable record deletion behaviour

### ISSUE THREAD

**Issue by jmartinm** [inveniosoftware/invenio-records#150]
Currently, when performing a 'soft-deletion' of a record, the `json` column is emptied ([See lines](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/api.py#L307-L308))

The issue with this can be:

1) Recreating records in ES from DB. As there is no JSON, the record will not be sent to ES and thus will not be searchable. Might be useful to keep deleted records in ES to do some searches on them.

2) In a future record editor, where we load records from DB, extra logic will have to be added in order to fetch the record, e.g from the last non-empty history entry. Instead if the record stayed in DB the record would be opened normally and could be un-deleted.

Would it be possible to make this configurable or leave the records still in the DB when soft deleting?

**Comment by jirikuncar** [comment]
@jmartinm you can change your indexer to get last not deleted revision instead on current record.

**Comment by lnielsen** [comment]
I think the API is good and clear as-is today and that changing the current behaviour will lead to muddy picture of what is a deleted record. Consider:

- Deleted record: ``model.json = None``
- Empty record: ``model.json = {}``

Actually I think your issue is rather a Records/PIDStore usage problem. If you need to access a record, then you should not delete the record. You can either clear the record (``record.clear()``) if you want an empty record, or you can just leave the record as-is. Then in PIDStore you can delete the PID(s) referencing the record which will ensure that they are no longer accessible. 

Once example of this is e.g. Records-UI's display of tombstone pages for deleted records. The PID is marked deleted. The record can either be deleted or not. E.g. on Zenodo I do not delete the record, but store a "removal reason" inside the record, which can then be displayed on the tombstone page with a 410 Gone HTTP error code. See https://github.com/inveniosoftware/invenio-records-ui/blob/master/invenio_records_ui/views.py#L65-L71

**Comment by kaplun** [comment]
@lnielsen so you basically ensure you never use `Record.delete()` API in Zenodo, right?

**Comment by lnielsen** [comment]
@kaplun Correct.

**Comment by jmartinm** [comment]
Since there seem to be alternative solutions I can close this. Thanks for the comments.
