### ISSUE TITLE
api: patch record not behaving as expected

### ISSUE THREAD

**Issue by eamonnmag** [inveniosoftware/invenio-records#21]
Record.patch currently returns a patched data object, but has no impact on the database record. This is misleading as far as an API call goes. 

I would propose this (open of course to suggestions for improvements) 

``` python
def patch(self, patch):
        model = self.model
        data = apply_patch(dict(self), patch)
        # perform the commit on the patched data.

        try:
            patched_record = self.__class__(data, model=model)
            patched_record.commit()
            return patched_record
        except Exception:
            raise
```

It would also be good to perhaps return back an updated version of the Record object rather than a new instance.

**Comment by dset0x** [comment]
It's worth noting that `jsonpatch.apply_patch(src, dst, in_place=True)` will not touch any attributes of the record, so splitting the `model` from the `data` seems superfluous.

> It would also be good to perhaps return back an updated version of the Record object rather than a new instance.

Ideally, yes, the user would have the same object reference. This may be a bit tricky to get right however, since we'd have to not instantiate a new SQLAlchemy, potentially skipping some initialization code.

---

Speaking of this function, is it within the scope of `invenio-records` to optionally also safeguard against patches that are directed to older versions of the record (ie provide some kind of atomic operation so that we know we're modifying the record version that we intend to).

**Comment by lnielsen** [comment]
Is this still relevant with the latest alpha release (i.e. 1.0.0)?

In general db changes are not persisted until calling ``db.session.commit()``. Record changes are flushed to the underlying JSON model on ``record.commit()``.

**Comment by jirikuncar** [comment]
This is a documentation issue (#65).
