### ISSUE TITLE
cli: removal of `input_type` argument for `create` command

### ISSUE THREAD

**Issue by jirikuncar** [inveniosoftware/invenio-records#50]
## Proposal

Use UNIX philosophy and combine utilities as follows:

```console
$ wget http://demo.invenio-software.org/search?of=xm -O | \
dojson -t dojson.contrib.marc21:marc21 | inveniomanage records create 
```

--
cc @lnielsen @nharraud

**Comment by lnielsen** [comment]
:+1: I guess both works:

``inveniomanage records create``
and
``inveniomanage records create <file>``

(i.e. file not specified means read from stdout

**Comment by egabancho** [comment]
does this mean that the [`convert_marcxml`](https://github.com/inveniosoftware/invenio-records/blob/master/invenio_records/manage.py#L37) would go somewhere else? DoJSON? overlay?

**Comment by jirikuncar** [comment]
@lnielsen yes, but no conversion allowed in records module.

```
inveniomanage records create [-f/--file [STDIN]]
```

**Comment by jirikuncar** [comment]
@egabancho I would add it to *DoJSON* package.

**Comment by nharraud** [comment]
I took a look at the command's code. If I understand correctly the change is mainly forcing input_type to json. I'm ok with that.

Regarding the command example I'm not sure to understand how it works. What does `wget http://demo.invenio-software.org/search?of=xm -O` output? Just the metadata or also other info like the database ID and the schema reference?
If not, how do you keep the same ID when exporting and reimporting? It would be great if it was possible so that the links remain valid.

**Comment by nharraud** [comment]
Sorry didn't think about trying it myself.

**Comment by nharraud** [comment]
For MARC21 it works because there is a field for the "control number". I'm wondering what will happen for future versions, once the records won't be bounded to marc21. How do we interpret them? Do we configure somewhere which json path contains the `id`? Or will there always be a way to convert them to marc21?

**Comment by nharraud** [comment]
The solution I would see is to separate invenio's metadata from the record's metadata and have a format similar to elasticsearch batch. (https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html)
There would always be two json one after the other. The first contains Invenio's metadata and the second contains record's metadata.

**Comment by lnielsen** [comment]
Fixed AFAIK?
